# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

# [print_schema]
# file = "packages/camrete-core/src/schema.rs"
# custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]
# patch_file = "packages/camrete-core/src/schema.patch"

[migrations_directory]
dir = "migrations"
