[package]
name = "camrete"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
camrete-core = { path = "../camrete-core" }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "macros"] }
miette = { version = "7.6.0", features = ["fancy"] }
clap = { version = "4.5.53", features = ["derive"] }
url = "2.5.7"
indicatif = "0.18.3"
thiserror = "2.0.17"
owo-colors = "4.2.3"
time = { version = "0.3.44", features = ["formatting"] }
termimad = "0.34.0"
